### ISSUE TITLE
Advanced API: Condition with varchar value fails

### ISSUE THREAD

**Issue by nesnoj** [openego/oeplatform#271]
I'm using the advanced API to retrieve some data.

Using a condition on a **numeric (serial) column** works:
```
import requests
data = { "query": {"fields": ['id', {'type': 'function', 'function': 'ST_AsText', 'operands':[{'type': 'column', 'column': 'geom'}]}],
                   "where": [{'type': 'operator', 'operator': '=', 'operands':[{'type': 'column', 'column': 'id'}, {'type': 'value', 'value': 1}]}],
                   "from":{'type': 'table', 'table': 'bkg_vg250_4_krs', 'schema':"boundaries"}}}
response = requests.post('http://oep.iks.cs.ovgu.de/api/v0/advanced/search', json=data)
data = response.json()['data']
print(data)
```

But not using a condition on a **non-numeric (varchar) column**:
```
import requests
data = { "query": {"fields": ['id', {'type': 'function', 'function': 'ST_AsText', 'operands':[{'type': 'column', 'column': 'geom'}]}],
                   "where": [{'type': 'operator', 'operator': '=', 'operands':[{'type': 'column', 'column': 'nuts'}, {'type': 'value', 'value': 'DEE05'}]}],
                   "from":{'type': 'table', 'table': 'bkg_vg250_4_krs', 'schema':"boundaries"}}}
response = requests.post('http://oep.iks.cs.ovgu.de/api/v0/advanced/search', json=data)
data = response.json()['data']
print(data)
```
(result is empty)

What's the matter here?

Update: Oh, there might be [some stuff left](https://github.com/openego/oeplatform/blob/cf9033206d2235339a0a299d84c1315260d28cf0/api/parser.py#L32) to be done..?!

**Comment by nesnoj** [comment]
After the PR #272 merge, I get an exception:
```
Traceback (most recent call last):
  File "/home/jonathan/git-repos/windnode/WindNODE_ABW/windnode_abw/model/region/test.py", line 59, in <module>
    data1 = response.json()['data']
  File "/home/jonathan/virtualenvs/windnode/windnode_abw/lib/python3.5/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by MGlauer** [comment]
This occurs likely, because the server returned a HTTP500, which does not have a JSON-like content. From what I see in the logs, this is because otg_ehvhv_bus_data does not have a column 'nuts'. I will add a corresponding error message.

**Comment by nesnoj** [comment]
Uh, obviously I used the wrong table for the last test. The 2nd query above works now too.
Thank's a lot for the quick fix!
